### ISSUE TITLE
A few bugs that related to both performance and quality

### ISSUE THREAD

**Issue by Bachender9008** [Scarlaid/P-QoL#6]
- No animations when breaking block 
- Fullscreen Resolution feature is not working ( reloaded )
- Leaves Quality are still Fancy despite the fact that it was set to Default ( Fast graphics ) and Fast

**Comment by Scarlaid** [comment]
Can you provide me a video/GIF reproducing the issues you're facing?

Through the context, I can answer only the 3rd question, is because this mod is standalone, which means even with fancy/fast/fabulous graphics settings, the leaves will **always** stay in Smart settings, not Fancy settings

If you find it annoying, here are the steps
- Go to your `Option` in your `Game Menu`
- IF you still keeping **Puzzle**, there will be a small puzzle icon next to your FOV slidebar, press it
- Go to Performance Settings
- Turn off Cull Leaves 
- Go to your resource pack and remove the Cull Leaves resource pack

For the 2nd question, it's **Borderless Fullscreen**, which your game wont be tabbed out while you change to other windows, please provide a video/GIF of which didn't function
Same with the first question, I don't understand the problem you are facing, like **the player swinging animation is gone** or **the chest animation is gone** or anything

Good day.

**Comment by Scarlaid** [comment]
Closed due to inactivity

**Comment by Bachender9008** [comment]
> Can you provide me a video/GIF reproducing the issues you're facing?
> 
> Through the context, I can answer only the 3rd question, is because this mod is standalone, which means even with fancy/fast/fabulous graphics settings, the leaves will **always** stay in Smart setting, not Fancy setting
> 
> If you find it annoying, here are the steps
> 
> * Go to your `Option` in your `Game Menu`
> * IF you still keeping **Puzzle**, there will be a small puzzle icon next to your FOV slidebar, press it
> * Go to Performance Settings
> * Turn off Cull Leaves
> * Go to your resource pack and remove the Cull Leaves resource pack
> 
> For the 2nd question, it's **Borderless Fullscreen**, which your game wont be tabbed out while you change to other windows, please provide a video/GIF of which didn't function Same with the first question, I don't understand the problem you are facing, like **the player swinging animation is gone** or **the chest animation is gone** or anything
> 
> Good day.

Sorry but what do you mean "your game wont be tabbed out while you change to other windows"?

**Comment by Scarlaid** [comment]
> > Can you provide me a video/GIF reproducing the issues you're facing?
> > Through the context, I can answer only the 3rd question, is because this mod is standalone, which means even with fancy/fast/fabulous graphics settings, the leaves will **always** stay in Smart setting, not Fancy setting
> > If you find it annoying, here are the steps
> > 
> > * Go to your `Option` in your `Game Menu`
> > * IF you still keeping **Puzzle**, there will be a small puzzle icon next to your FOV slidebar, press it
> > * Go to Performance Settings
> > * Turn off Cull Leaves
> > * Go to your resource pack and remove the Cull Leaves resource pack
> > 
> > For the 2nd question, it's **Borderless Fullscreen**, which your game wont be tabbed out while you change to other windows, please provide a video/GIF of which didn't function Same with the first question, I don't understand the problem you are facing, like **the player swinging animation is gone** or **the chest animation is gone** or anything
> > Good day.
> 
> Sorry but what do you mean "your game wont be tabbed out while you change to other windows"?

It means your game won't be closed down when you TabAlt

**Comment by Scarlaid** [comment]
For the Fullscreen Resolution, please provide a picture/video/gif please

**Comment by Bachender9008** [comment]
> For the Fullscreen Resolution, please provide a picture/video/gif please

I have some problems with screen recorders so i can't provide videos
![2022-02-20_19 44 44](https://user-images.githubusercontent.com/99522860/154843173-fa7bde89-bb84-484b-826f-2b8a9d0f38c4.png)
![2022-02-20_19 45 00](https://user-images.githubusercontent.com/99522860/154843176-2f63459f-a14a-4c1b-aa7e-857386925b86.png)

About my 1st question, it is like if you break a block, there would be some particles visible but here, no particles visible
